
## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: build rust beam
  run: 'cargo build'
  change: 'src/**'
  run_on_init: true
